services:
  # expo:
  #   build: ./app
  #   volumes:
  #     - ./app:/app
  #     - /app/node_modules
  #   environment:
  #     BASE_URL: http://localhost:8082
  #     WEB_PORT: 8082
  #     NODE_ENV: development
  #     CHOKIDAR_USEPOLLING: true
  #   ports:
  #     - "8082:8082"
  #   depends_on:
  #     - api

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ~/.ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    networks:
      - app-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  api:
    env_file: 
      - ./.env/api.env
    build: ./api
    environment: 
      - OLLAMA_HOST=http://ollama:11434
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - ollama
    volumes:
      - ./api:/api
    networks:
      - app-network

  mongodb:
    image: mongo
    env_file: 
      - ./.env/mongo.env
    restart: always
    volumes:
      - audhd:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    env_file: 
      - ./.env/mexpress.env
    ports:
      - 8081:8081
    environment:
      WAIT_HOSTS: mongodb:27017
    depends_on:
      - mongodb
  
  test:
    build: ./api
    env_file:
      - ./.env/api.env
    depends_on:
      - mongodb
    volumes:
      - ./api:/api
    command: poetry run pytest tests/ -v --asyncio-mode=auto --cov=.
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - PYTHONPATH=/api

volumes:
  audhd:
  ollama:

networks:
  app-network:
    driver: bridge
  